### ISSUE TITLE
plz help me

### ISSUE THREAD

**Issue by PhamtomK12** [JakobKlocker/IRC_Server#1]
Dr JakobKlocker
I downloaded the  NexonGameSecurity-Bypass file last month, but it has been deleted now, can you resend it to me for learning, thank you.

email huaxia.guoluren@gmail.com

**Comment by JakobKlocker** [comment]
It is not available anymore.

**Comment by zgrwq** [comment]
Dr JakobKlocker
I downloaded the NexonGameSecurity-Bypass file last month, but it has been deleted now, can you resend it to me for learning, thank you. email puggszgr@gmail.com
